### ISSUE TITLE
CRAN release Checklist

### ISSUE THREAD

**Issue by DirkMittelstrass** [DirkMittelstrass/OSLdecomposition#2]
As this package is meant for a release at the CRAN server in ~~Mid-December 2020~~ January 2022, there are some ToDo's left.:

- ~~create (and test) a tutorial to publish it in the vignette, at luminescence.de and in the GitHub Wiki~~ (The tutorial at [luminescence.de/](https://luminescence.de/OSL_tutorial.html) should be enough for now)
- ~~Spell- and style-check the documentation and the automatic reports~~ (_Many thanks to @eiskeil for the review_)
- ~~Re-iterate `sum_OSLcurves()`. A list of `data.frame` or `matrix` objects should be accepted~~
    (_skipped for now; not of importance for basic users and a solvable issue of advanced users_)
- ~~`RLum.OSL_correction()` contains unused parameters. Activate them or (temporally) remove them~~ (Pulse-pair correction works now. Check signal level is removed)
- ~~Provide working but fast script examples for all functions for the CRAN tests~~
- ~~Solve that strange bug about auto-naming the output folder for the reports~~ (Solved)
- ~~Move `rmarkdown` and `kableExtra` from _Imports_ to _Suggests_ and test their availability in the code.~~ (Done this for kableExtra but not for rmarkdown. Package should now run on Ubuntu smoothly)

I will strike out the points as they are solved. If I missed something, please write a comment.

**Comment by RLumSK** [comment]
> Solve that strange bug about auto-naming the output folder for the reports

@DirkMittelstrass What do you mean here?

**Comment by DirkMittelstrass** [comment]
@RLumSK The HTML reports are saved correctly in the `report_dir` path. However, the images for the report might be saved in the parent directory of the target directory.

Btw: I striked out three points and added another. The package is not dead :-)
